AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.7

Style/FrozenStringLiteralComment:
  SafeAutoCorrect: true

Style/StringLiterals:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Layout/RedundantLineBreak:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - 'spec/**/*'

Style/Copyright:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

