AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.7

Style/StringLiterals:
  Enabled: false

Layout/MultilineAssignmentLayout:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/MethodCalledOnDoEndBlock:
  Exclude:
    - 'spec/**/*'